import type { NextPage } from 'next'
import Head from 'next/head'
import s from 'styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={s.mainHello}>Hello and welcome</h1>
      </main>
    </>
  )
}

export default Home
